version: "3.4"
services:
  springdb:
    image: bitnami/postgresql:11
    restart: on-failure
    volumes:
      - springdb:/bitnami/postgresql
    networks:
      - sprintestnet
    ports:
      - 5432:5432
    environment:
      - "POSTGRESQL_DATABASE=springdb"
      - "POSTGRESQL_USERNAME=springusr"
      - "POSTGRESQL_PASSWORD=123123"
volumes:
  springdb:
networks:
  sprintestnet:
    driver: bridge